### ISSUE TITLE
clone下来的demo运行pod install报错呢？

### ISSUE THREAD

**Issue by bajiejiedian** [jiisd/YHFlutterAdapter#4]

**Comment by jiisd** [comment]
请问你的报错信息是什么呢？

```
➜  YHFlutterAdapter git:(master) pod --version
1.5.3
➜  YHFlutterAdapter git:(master) cd Demo
➜  Demo git:(master) pod install
Analyzing dependencies
Downloading dependencies
Using YHFlutterAdapter (0.0.3)
Using YHFlutterPlugin (0.0.3)
Using YHFlutterSDK (0.0.3)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.
```

**Comment by spemagic** [comment]
[!] Error installing YHFlutterAdapter
[!] /usr/bin/git clone git@github.com:jiisd/YHFlutterAdapter.git /var/folders/63/7wms24hn59j83499x4yw1w6h0000gn/T/d20190220-4901-m8nf73 --template= --single-branch --depth 1 --branch 0.0.3

Cloning into '/var/folders/63/7wms24hn59j83499x4yw1w6h0000gn/T/d20190220-4901-m8nf73'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by DDingDreams** [comment]
[!] Error installing YHFlutterAdapter
[!] /usr/local/bin/git clone git@github.com:jiisd/YHFlutterAdapter.git /var/folders/ks/b1qcy1jx70l2kx5cz6d3vkvr0000gn/T/d20190606-87706-s8qeir --template= --single-branch --depth 1 --branch 0.0.3

Cloning into '/var/folders/ks/b1qcy1jx70l2kx5cz6d3vkvr0000gn/T/d20190606-87706-s8qeir'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jiisd** [comment]
@DDingDreams 有没有配置 github 的 ssh？
或者将 demo 内的 Podfile 修改为本地引用
>pod 'YHFlutterSDK',        :path => '../YHFlutterSDK'
>pod 'YHFlutterAdapter',    :path => '../YHFlutterAdapter'
>pod 'YHFlutterPlugin',     :path => '../YHFlutterPlugin'

**Comment by DDingDreams** [comment]
谢谢，解决了。我这个报错应该是我的git配置有问题。
