### ISSUE TITLE
你的这个flutterviewcontroller 没有走dealloc

### ISSUE THREAD

**Issue by lihui2333** [jiisd/YHFlutterAdapter#6]
flutter 官方之前有这个bug flutterviewcontroller 不能释放的问题  你这个demo里面的 就没有走过dealloc

**Comment by jiisd** [comment]
Flutter 被设计的目的主要是为了实现一个全局完整的 APP，就算官方已经解决了之前的内存泄漏问题目前也不建议在一个 APP 内实例化出多个 Flutter 界面，连续显示多个 Flutter 界面的场景下，内存占用太高；
